import type { HomeModule } from "@/features/home-world/types";

const unsortedHomeModules: HomeModule[] = [
  {
    id: "about",
    title: "关于我小屋",
    route: "/about",
    intro: "认识这个数字花园的主人。",
    position: [-2.5, 0, 0.4],
    color: "#f6b26b",
    accentColor: "#ffe2b7",
    houseStyle: "cottage",
    placeholderStyle: "cottage",
    assetKey: "lowPolyCafe",
    visibility: "public",
    sortOrder: 1,
  },
  {
    id: "thoughts",
    title: "博客图书馆",
    route: "/thoughts",
    intro: "日常想法、阶段情绪和长一点的自我记录。",
    position: [-1.3, 0, -1.2],
    color: "#d66b5f",
    accentColor: "#ffe0b5",
    houseStyle: "tower",
    placeholderStyle: "library",
    assetKey: "houseBuildingLowPoly",
    visibility: "public",
    sortOrder: 2,
  },
  {
    id: "album",
    title: "技能温室",
    route: "/album",
    intro: "照片不是证据，是当时心情的标本。",
    position: [1.3, 0, -1.2],
    color: "#8fd6c8",
    accentColor: "#d8fff6",
    houseStyle: "gallery",
    placeholderStyle: "greenhouse",
    assetKey: "isometricCinema",
    visibility: "public",
    sortOrder: 3,
  },
  {
    id: "playlists",
    title: "项目工坊",
    route: "/playlists",
    intro: "把循环过很多遍的歌和当时的感触放在一起。",
    position: [2.5, 0, 0.4],
    color: "#6fa8dc",
    accentColor: "#cfe8ff",
    houseStyle: "music",
    placeholderStyle: "workshop",
    assetKey: "isometricMall",
    visibility: "public",
    sortOrder: 4,
  },
  {
    id: "todo",
    title: "经历塔楼",
    route: "/todo",
    intro: "一些想做的事，以及已经完成的小小里程碑。",
    position: [1.35, 0, 1.55],
    color: "#c98f5a",
    accentColor: "#ffcf8f",
    houseStyle: "cottage",
    placeholderStyle: "tower",
    assetKey: "coffeeShopIsometric",
    visibility: "public",
    sortOrder: 5,
  },
  {
    id: "message",
    title: "联系邮局",
    route: "/message",
    intro: "如果你路过这里，也可以留下一点声音。",
    position: [-1.35, 0, 1.55],
    color: "#ef8f8f",
    accentColor: "#ffd6c7",
    houseStyle: "mailbox",
    placeholderStyle: "mail",
    assetKey: "fastFoodRestaurant",
    visibility: "public",
    sortOrder: 6,
  },
];

export const homeModules = unsortedHomeModules.sort((a, b) => a.sortOrder - b.sortOrder);
