import type { HomeModule } from "@/features/home-world/types";

const unsortedHomeModules: HomeModule[] = [
  {
    id: "about",
    title: "关于我",
    route: "/about",
    intro: "认识这个数字花园的主人。",
    position: [-2.8, 0, -0.6],
    color: "#ff8fab",
    accentColor: "#ffd6e2",
    houseStyle: "cottage",
    visibility: "public",
    sortOrder: 1,
  },
  {
    id: "thoughts",
    title: "碎碎念",
    route: "/thoughts",
    intro: "日常想法、阶段情绪和长一点的自我记录。",
    position: [-1.1, 0, -2.1],
    color: "#9b5de5",
    accentColor: "#d7b6ff",
    houseStyle: "tower",
    visibility: "public",
    sortOrder: 2,
  },
  {
    id: "album",
    title: "相册",
    route: "/album",
    intro: "照片不是证据，是当时心情的标本。",
    position: [1.2, 0, -2.0],
    color: "#00bbf9",
    accentColor: "#b7f3ff",
    houseStyle: "gallery",
    visibility: "public",
    sortOrder: 3,
  },
  {
    id: "playlists",
    title: "歌单",
    route: "/playlists",
    intro: "把循环过很多遍的歌和当时的感触放在一起。",
    position: [3.0, 0, -0.4],
    color: "#f15bb5",
    accentColor: "#ffc4eb",
    houseStyle: "music",
    visibility: "public",
    sortOrder: 4,
  },
  {
    id: "todo",
    title: "人生 Todo",
    route: "/todo",
    intro: "一些想做的事，以及已经完成的小小里程碑。",
    position: [1.8, 0, 1.6],
    color: "#fee440",
    accentColor: "#fff4a3",
    houseStyle: "cottage",
    visibility: "public",
    sortOrder: 5,
  },
  {
    id: "message",
    title: "留言",
    route: "/message",
    intro: "如果你路过这里，也可以留下一点声音。",
    position: [-1.7, 0, 1.7],
    color: "#00f5d4",
    accentColor: "#b8fff4",
    houseStyle: "mailbox",
    visibility: "public",
    sortOrder: 6,
  },
];

export const homeModules = unsortedHomeModules.sort((a, b) => a.sortOrder - b.sortOrder);
