import type { HomeModule } from "@/features/home-world/types";

const unsortedHomeModules: HomeModule[] = [
  {
    id: "about",
    title: "个人相册",
    route: "/album",
    intro: "收集照片、片段和当下想留住的画面。",
    position: [-2.5, 0, 0.4],
    color: "#f6b26b",
    accentColor: "#ffe2b7",
    houseStyle: "cottage",
    placeholderStyle: "cottage",
    assetKey: "lowPolyCafe",
    visibility: "public",
    sortOrder: 1,
  },
  {
    id: "thoughts",
    title: "碎碎念",
    route: "/thoughts",
    intro: "放一点日常想法、情绪和不成篇的记录。",
    position: [-1.3, 0, -1.2],
    color: "#d66b5f",
    accentColor: "#ffe0b5",
    houseStyle: "tower",
    placeholderStyle: "library",
    assetKey: "houseBuildingLowPoly",
    visibility: "public",
    sortOrder: 2,
  },
  {
    id: "museum",
    title: "歌单",
    route: "/playlists",
    intro: "把循环播放过的歌和当时的心情放在一起。",
    position: [0, 0, -1.95],
    color: "#c98f5a",
    accentColor: "#ffcf8f",
    houseStyle: "cottage",
    placeholderStyle: "cottage",
    assetKey: "lowPolyApartmentBuilding3",
    visibility: "public",
    sortOrder: 3,
  },
  {
    id: "album",
    title: "心情日记",
    route: "/about",
    intro: "记录一些不想被快速略过的情绪起伏。",
    position: [1.3, 0, -0.9],
    color: "#8fd6c8",
    accentColor: "#d8fff6",
    houseStyle: "gallery",
    placeholderStyle: "greenhouse",
    assetKey: "lowPolyBuilding",
    visibility: "public",
    sortOrder: 4,
  },
  {
    id: "playlists",
    title: "咖啡推荐",
    route: "/coffee",
    intro: "留给喜欢的咖啡店、豆子和风味笔记。",
    position: [2.75, 0, -0.05],
    color: "#6fa8dc",
    accentColor: "#cfe8ff",
    houseStyle: "music",
    placeholderStyle: "workshop",
    assetKey: "coffeeShopIsometric",
    visibility: "public",
    sortOrder: 5,
  },
  {
    id: "todo",
    title: "人生todolist",
    route: "/todo",
    intro: "把想做的事和已经完成的小里程碑放进清单里。",
    position: [1.35, 0, 1.55],
    color: "#c98f5a",
    accentColor: "#ffcf8f",
    houseStyle: "cottage",
    placeholderStyle: "tower",
    assetKey: "isometricMall",
    visibility: "public",
    sortOrder: 6,
  },
  {
    id: "message",
    title: "学习笔记",
    route: "/message",
    intro: "沉淀学到的东西，顺手留下一些可回看的笔记。",
    position: [-1.35, 0, 1.55],
    color: "#ef8f8f",
    accentColor: "#ffd6c7",
    houseStyle: "mailbox",
    placeholderStyle: "mail",
    assetKey: "fastFoodRestaurant",
    visibility: "public",
    sortOrder: 7,
  },
];

export const homeModules = unsortedHomeModules.sort((a, b) => a.sortOrder - b.sortOrder);
